services:
  - type: web
    name: smartcontainer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PIP_INDEX_URL
        value: "https://pypi.org/simple"
      - key: PIP_USER
        value: "0"